name: Crowdin - Upload and Download strings
on:
    push:
        branches:
        -   develop
        paths:
        -   '**.py'
    workflow_dispatch:


jobs:
    crowdin:
        if: github.repository == 'PyLav/PyLav'
        runs-on: [ubuntu-latest]
        name: Upload the latest strings to Crowdin
        concurrency:
            group: crowdin
            cancel-in-progress: true
        steps:
        -   name: Sleep for 5 minutes
            uses: jakejarvis/wait-action@master
            with:
                time: 5m
        -   uses: actions/checkout@v4.1.6
            with:
                ref: develop
                token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        -   name: Set up Python
            uses: actions/setup-python@v5
            with:
                python-version: '3.11'
        -   name: Install dependencies
            run: |
                pip install redgettext==3.4.2
        -   name: Generate source files
            run: |
                python3.11 -m redgettext --command-docstrings --verbose --recursive .
        -   name: crowdin action
            uses: crowdin/github-action@v1.20.2
            with:
                upload_sources: true
                upload_translations: false
                download_translations: true
                pull_request_labels: i18n, translations, automerge
            env:
                CROWDIN_API_KEY: ${{ secrets.crowdin_token}}
                CROWDIN_PROJECT_ID: ${{ secrets.crowdin_identifier }}
                GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
